title: Workfare
url: https://www.open.gov.sg
favicon: /images/horizontal logos(rendered for wed).png
colors:
  primary-color: "#309449"
  secondary-color: "#309449"
  media-colors:
    - title: media-color-one
      color: "#8abf37"
    - title: media-color-two
      color: "#8abf37"
    - title: media-color-three
      color: "#cd38b1"
    - title: media-color-four
      color: "#74ad0d"
    - title: media-color-five
      color: "#399339"
resources_name: newsroom
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
description: Workfare provides additional support to lower-income Singaporeans
  who continue working and training through Workfare Income Supplement (WIS)
  Scheme and Workfare Skills Support (WSS) Scheme.
staging: https://cpf-workfare-staging.netlify.com
prod: https://cpf-workfare-prod.netlify.com
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
shareicon: /images/banner_home_1.jpg
is_government: true
facebook-pixel: ""
google_analytics_ga4: ""
linkedin-insights: ""
